import streamlit as st

st.title("Indra")
st.write("menjalani hari hari biasa dengan bersekolah")
st.sidebar.title("Settings")
st.sidebar.markdown("new add")
st.sidebar.markdown("gender")
st.sidebar.radio("gender",["male","female"])
st.title("This is the app title")
st.header("This is the header")
st.markdown("This is the markdown")
st.subheader("This is the subheader")
st.caption("This is the caption")
st.code("x = 2021")
st.latex(r''' a+a r^1+a r^2+a r^3 ''')
